FROM ubuntu:18.04

MAINTAINER Ahmed Balata

# Setup
RUN apt-get update && apt-get install -y \
            wget \
            lib32ncurses5 \
            make \
            python-pip \
	    python-serial \
            automake \
            sudo


#install arm-gcc
RUN sudo apt-get update -y && \
	sudo apt-get install -y gcc-arm-none-eabi






